import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :local_hospital_service, LocalHospitalServiceWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: LocalHospitalService.Finch

# Keep enabled Swoosh Local Memory Storage
# Note: This is a redundant option, but I keep it explicitly here since toggling it off would cause a
# "Swoosh.Adapters.Local.Storage.Memory the process is not alive" error when sending emails
config :swoosh, local: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Enable dev routes for dashboard and mailbox
# NOTE: This is for practicity when performing demos for the application,
# in a real-world scenario, this should not be publicly accessible
config :local_hospital_service, dev_routes: true
